package io.quarkiverse.quarkus.scylladb.orm.it.processor;

import static org.junit.jupiter.api.Assertions.*;

import java.util.List;
import java.util.Map;
import java.util.UUID;

import jakarta.inject.Inject;

import org.junit.jupiter.api.Test;

import io.quarkiverse.quarkus.scylladb.orm.it.model.Address;
import io.quarkiverse.quarkus.scylladb.orm.it.model.AddressMapper;
import io.quarkiverse.quarkus.scylladb.orm.it.model.Person;
import io.quarkiverse.quarkus.scylladb.orm.it.model.PersonMapper;
import io.quarkiverse.quarkus.scylladb.orm.mapping.KeyComponent;
import io.quarkus.test.junit.QuarkusTest;

@QuarkusTest
class MapperTest {

    @Inject
    PersonMapper personMapper;

    @Inject
    AddressMapper addressMapper;

    @Test
    void testMapperExists() {
        assertNotNull(personMapper);
        assertNotNull(addressMapper);
    }

    @Test
    void testMapperToDb() {
        Person person = new Person();
        person.setId(UUID.randomUUID());
        person.setName("John Doe");
        person.setAddressId(UUID.randomUUID());
        Map<String, Object> dbMap = personMapper.toProperties(person);

        assertNotNull(dbMap);
        assertEquals(3, dbMap.size());

        assertEquals("John Doe", dbMap.get("name"));
        assertEquals(person.getId(), dbMap.get("id"));
        assertEquals(person.getAddressId(), dbMap.get("address_id"));
    }

    @Test
    void testMapperToDbNullFields() {
        Person person = new Person();
        person.setId(UUID.randomUUID());

        Map<String, Object> dbMap = personMapper.toProperties(person);

        assertNotNull(dbMap);
        assertTrue(dbMap.containsKey("id"));
        assertFalse(dbMap.containsKey("name"));
        assertFalse(dbMap.containsKey("address_id"));
    }

    @Test
    void testPartitionKeyNames() {
        String[] pkNames = personMapper.getPartitionKeyNames();

        assertNotNull(pkNames);
        assertEquals(1, pkNames.length);
        assertEquals("id", pkNames[0]);
    }

    @Test
    void testClusteringKeyNames() {
        String[] ckNames = personMapper.getClusteringKeyNames();

        assertNotNull(ckNames);
        assertEquals(0, ckNames.length);
    }

    @Test
    void testPartitionKeyComponents() {
        UUID id = UUID.randomUUID();
        Person person = new Person();
        person.setId(id);

        List<KeyComponent<?>> pkComponents = personMapper.getPartitionKeyComponents(person);

        assertNotNull(pkComponents);
        assertEquals(1, pkComponents.size());
        assertEquals("id", pkComponents.get(0).name());
        assertEquals(id, pkComponents.get(0).value());
        assertEquals(0, pkComponents.get(0).ordinal());
    }

    @Test
    void testClusteringKeyComponents() {
        Person person = new Person();
        person.setId(UUID.randomUUID());

        List<KeyComponent<?>> ckComponents = personMapper.getClusteringKeyComponents(person);

        assertNotNull(ckComponents);
        assertTrue(ckComponents.isEmpty());
    }

    @Test
    void testEntityType() {
        assertEquals(Person.class, personMapper.getEntityType());
        assertEquals(Address.class, addressMapper.getEntityType());
    }

    @Test
    void testAutoGenerateUuidOnToProperties() {
        Person person = new Person();
        assertNull(person.getId());

        Map<String, Object> dbMap = personMapper.toProperties(person);

        assertNotNull(person.getId(), "UUID should be auto-generated by toProperties");
        assertTrue(dbMap.containsKey("id"));
        assertEquals(person.getId(), dbMap.get("id"));
    }

    @Test
    void testAddressMapperToDb() {
        Address address = new Address();
        address.setId(UUID.randomUUID());
        address.setStreet("Test Street");
        address.setHousenumber("123");

        Map<String, Object> dbMap = addressMapper.toProperties(address);

        assertNotNull(dbMap);
        assertEquals(3, dbMap.size());
        assertEquals(address.getId(), dbMap.get("id"));
        assertEquals("Test Street", dbMap.get("street"));
        assertEquals("123", dbMap.get("housenumber"));
    }

    @Test
    void testAddressPartitionKeyNames() {
        String[] pkNames = addressMapper.getPartitionKeyNames();

        assertNotNull(pkNames);
        assertEquals(1, pkNames.length);
        assertEquals("id", pkNames[0]);
    }

    @Test
    void testPropertiesPreserveInsertionOrder() {
        Person person = new Person();
        person.setId(UUID.randomUUID());
        person.setName("Order Test");
        person.setAddressId(UUID.randomUUID());

        Map<String, Object> dbMap = personMapper.toProperties(person);

        List<String> keys = List.copyOf(dbMap.keySet());
        assertEquals("id", keys.get(0));
        assertEquals("name", keys.get(1));
        assertEquals("address_id", keys.get(2));
    }
}
